services:
  catalog.db:
    image: mongo
    container_name: catalog_db
  basket.db:
    image: redis:alpine
    container_name: basket_db
  discount.db:
    image: postgres:alpine
    container_name: discount_db
  order_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: order_db
  rabbit_mq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitMQ
  catalog_api:
    image: ${DOCKER_REGISTRY-}catalog_api
    container_name: catalog_api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  basket_api:
    image: ${DOCKER_REGISTRY-}basket_api
    container_name: basket_api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  discount_api:
    image: ${DOCKER_REGISTRY-}discount_api
    container_name: discount_api
    build:
      context: .
      dockerfile: Services/Discount/Discount.Api/Dockerfile
  ordering_api:
    image: ${DOCKER_REGISTRY-}ordering_api
    container_name: ordering_api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
  Portainer:
    image: portainer/portainer-ce
    container_name: Portainer

  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
  order_db_data:
  rabbitmq_data:

